Fix actual Git issue by cheating a lot

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,10 +1,17 @@
 #!/bin/bash
 
-if [[ -f $3/BUILD_GROUPME_BOT_ID ]]; then
-  bot_id=$(cat $3/BUILD_GROUPME_BOT_ID)
-  curl -X POST --data-urlencode "text=🤖🛠️ Reporting for duty! Last update: $(cd $1 && git log -1 --pretty=format:%s)" "https://api.groupme.com/v3/bots/post?bot_id=$bot_id"
-  echo "-----> GroupMe notification sent!"
-else
-  echo "-----> Environment variable BUILD_GROUPME_BOT_ID not found!"
-  exit 1
-fi
+get_env() {
+  if [[ -f $1/$2 ]]; then
+    cat $1/$2
+  else
+    echo "       Environment variable $2 not found!" >&2
+    exit 1
+  fi
+}
+
+echo "-----> Sending GroupMe notification..."
+sudo apt-get install -yy jq
+bot_id=$(get_env $3 BUILD_GROUPME_BOT_ID)
+gh_repo=$(get_env $3 BUILD_GITHUB_REPO)
+commit_msg=$(curl https://api.github.com/repos/$gh_repo/commits/$SOURCE_VERSION | jq '.commit.message')
+curl -X POST --data-urlencode "text=🤖🛠️ Reporting for duty! Last update: $commit_msg" "https://api.groupme.com/v3/bots/post?bot_id=$bot_id"
